name: Test Coverage Github Actions
on:
  push:
    branches:
      - tmp_test_coverage
  pull_request:
    branches:
      - master
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Prepare Env
        run: |
          sudo apt-get install g++ llvm
          curl -fsSL https://xmake.io/shget.text | bash
      - name: Run Tests
        run: |
          xmake f -p linux -a x64 -m debug -y
          xmake build -w cwheel_test
          cd build/linux/x86_64/debug
          ./cwheel_test
          
      - name: Upstream to codecov
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
        run: |
          curl -S -f https://codecov.io/bash -o codecov
          chmod +x codecov
          ./codecov -x "llvm-cov gcov" -Z -t ${token}