name: Test Coverage Github Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-and-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Prepare Env
        run: |
          sudo apt-get install llvm clang lcov
          curl -fsSL https://xmake.io/shget.text | bash
      - name: Run Tests
        run: |
          xmake f -p linux -a x64 -m coverage --test=y -y
          xmake build -w cwheel_test
          xmake run cwheel_test 
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
          lcov -e coverage.info '*cwheel/*' --output-file coverage.info
          lcov --list coverage.info
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} 
          files: ./coverage.info
          flags: unittests
          fail_ci_if_error: true 